#!/bin/bash

if ! [ -d "$1" ]; then
       mkdir "$1"
fi
cd $1

todate=$(date +"%Y-%m-%d")
if ! [ -d "recon-$todate" ]; then
	mkdir "recon-$todate"
fi
cd "recon-$todate"

echo "[+] Enumerating subodmains with certspotter"
curl -s https://certspotter.com/api/v0/certs\?domain\=$1 | jq '.[].dns_names[]' | sed 's/\"//g' | sed 's/\*\.//g' | sort -u | grep $1 >> subdomains.txt

echo "[+] Enumerating subdomains with crtsh"
curl -s https://crt.sh/?Identity=%.$1 | grep ">*.$1" | sed 's/<[/]*[TB][DR]>/\n/g' | grep -vE "<|^[\*]*[\.]*$1" | sort -u | awk 'NF' >> subdomains.txt

echo "[+] Enumrating subdomains with assetfinder"
assetfinder -subs-only $1 | grep $1 >> subdomains.txt

echo "[+] Removing dupliicates"
sort -u subdomains.txt -o subdomains.txt

echo "[+] Enumerating third-domains"
cat subdomains.txt | xargs -n1 assetfinder --subs-only | tee -a third.txt
sort -u third.txt -o third.txt

echo "[+] Probing for alive domain"
cat subdomains.txt | httprobe >> alive.txt
sort -u alive.txt -o alive.txt
cat third.txt | httprobe >> third-alive.txt
sort -u third-alive.txt -o third-alive.txt

echo "[+] Job done"

