#!/bin/bash

### Made by @vnch31 ###

########## Edit your configuration here #######
eyewitness_path=~/tools/EyeWitness/Python/EyeWitness.py
masscan_rate=100000

###############################################

#Colors var
YELLOW="\033[1;33m"
GREEN="\033[0;32m"
RED="\033[0;31m"
BLUE="\033[0;34m"
BOLD="\033[1m"
RESET="\033[0m"

#Options var
date=0
port=0
fast=0
screen=0

help(){
	echo -e "./recon.sh -d domain.com [-p] [-t] [-f] [-s]\n Options:\n-p : port scan subdomains\n-s : Take screenshots of web services running on alive domains\n-f : fast scan (don't scan third level domains)\n-t : Create a dated folder containing recon information => recon-YEAR-MONTH-DAY" 1>&2; exit 1;
}

while getopts ":d:p:t:f:" o;do
	case "${o}" in
		d)
			domain=$OPTARG
			;;
		t)
			date=1
			;;
		p)
			port=1
			;;
		f)
			fast=1
			;;
		s)
			screen=1
			;;
	esac
done
shift $((OPTIND -1))

if (( $OPTIND == 1 )); then
   help
fi

if [ -z "$domain" ]; then
	help
fi

echo -e "$BLUE### Start scanning $BOLD $domain $BLUE ###${RESET}"

if ! [ -d "./$domain" ]; then
       mkdir "./$domain"
fi
cd ./$domain

if [ $date -eq 1 ]; then
	todate=$(date +"%Y-%m-%d")
	if ! [ -d "./recon-$todate" ]; then
		mkdir "./recon-$todate"
	fi
	cd "./recon-$todate"
fi

echo -e "$GREEN[+]$RESET Enumerating subodmains with certspotter"
curl -s https://certspotter.com/api/v0/certs\?domain\=$domain | jq '.[].dns_names[]' | sed 's/\"//g' | sed 's/\*\.//g' | sort -u | grep $domain >> subdomains.txt

echo -e "$GREEN[+]$RESET Enumerating subdomains with crtsh"
curl -s https://crt.sh/?Identity=%.$domain | grep ">*.$domain" | sed 's/<[/]*[TB][DR]>/\n/g' | grep -vE "<|^[\*]*[\.]*$domain" | sort -u | awk 'NF' >> subdomains.txt

echo -e "$GREEN[+]$RESET Enumerating subdomains with assetfinder"
assetfinder -subs-only $domain | grep $domain >> subdomains.txt

if [ $fast -eq 1 ]; then
	echo -e "$GREEN[+]$RESET Enumerating third levels domains"
	cat subdomains.txt | xargs -n1 assetfinder --subs-only >>  top-domains.txt
	sort -u top-domains.txt -o third.txt
	cat third.txt >> subdomains.txt
	rm third.txt top-domains.txt
fi

echo -e "$GREEN[+]$RESET Removing duplicates"
sort -u subdomains.txt -o subdomains.txt

echo -e "$GREEN[+]$RESET Probing for alive domain"
cat subdomains.txt | httprobe >> alive.txt
sort -u alive.txt -o alive.txt

echo -e "$GREEN[+]$RESET Checking old files on waybackmachines"
echo "$domain" | waybackurls > wayback.txt

if [ $port -eq 1 ]; then
	echo -e "$GREEN[+]$RESET Scanning alive domains's port"
	cat alive.txt | sed 's/https\?:\/\///' | uniq >> resolved.txt
	sudo masscan -iL subdomains.txt -p 0-65535 --max-rate $masscan_rate -n -Pn -oG ./masscan.txt 
	cat masscan.txt | grep "Ports: 80" >> https_ip.txt
	cat masscan.txt | grep "Ports: 443" >> https_ip.txt
	sort -u https_ip.txt -o https_ip.txt
	cat masscan.txt | grep -v "Ports: 80" | grep -v "Ports: 443" >> port_ip.txt
fi

if [ $screen -eq 1 ]; then
	python3 $eyewitness_path -f https_ip.txt --web
fi

echo -e "$BLUE### $BOLD $domain $BLUE scan is done ###$RESET"
